---
title: "Shape congruence of population, genetic, and environmental network topologies."
description: |
  Networks structures are common features in ecological and environmental anlyses because they conceptually fit into notions of connectivity and information flows between populations or across landscapes.
author:
  - name: Rodney J. Dyer
    url: https://dyerlab.org
    affiliation: Center for Environmental Studies<br>Virginia Commonwealth University<br>&nbsp;
    affiliation_url: https://ces.vcu.edu
    orcid_id: 0000-0003-4707-3453
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gstudio)
library(popgraph)
library(tidyverse)
```





This manuscript introduces several measures that can be used to quantify 




## Methods


```{r echo=FALSE}
files <- list.files(path="data/random_convergence",pattern = "graph_100*", full.names = TRUE )
graphs <- list() 
for(file in files ) { 
  load(file)
  graphs[[basename(file)]] <- g 
  g <- NULL 
}
```








## Localized similarities



### Connection Similarity



### Neighborhood Similarity



## Global Similarities


### Connectivity Similarity



What is the distribution of connectivityu values that produce a sturcture like this?



### Structural Congruence




### Distance Congruence